PUT  http://localhost:8080/api/company/
Content-Type: application/json
Authorization: Basic ykartal@ogu.edu.tr:sdfasdfadfasdfasdfasdf

{
  "id": 1,
  "name": "company2",
  "address": "companyAddress",
  "phoneNumber": "065465465",
  "faxNumber": "654984654",
  "email": "e@mail.com",
  "scope": "scope0",
  "description": "desc0"
}