POST http://localhost:8080/public/forgot-password
Content-Type: application/json
    
{
    "email":"ezgiozdikyar@gmail.com"
}

###

POST http://localhost:8080/public/update-password
Content-Type: application/json
    
{
    "hash":"5bd98b53-f434-4f90-bf80-c79e5826cb4d",
    "password":"12345",
    "confirmPassword": "12345"
}